// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
      appId: '1:687324217816:web:7be80cb0732c61bc0b32ad',
      messagingSenderId: '687324217816',
      projectId: 'sentinel360-final',
      authDomain: 'sentinel360-final.firebaseapp.com',
      storageBucket: 'sentinel360-final.firebasestorage.app',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
      appId: '1:687324217816:android:48fb5aa808d99e4b0b32ad',
      messagingSenderId: '687324217816',
      projectId: 'sentinel360-final',
      storageBucket: 'sentinel360-final.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
      appId: '1:687324217816:ios:49d746f5829cba230b32ad',
      messagingSenderId: '687324217816',
      projectId: 'sentinel360-final',
      storageBucket: 'sentinel360-final.firebasestorage.app',
      androidClientId:
          '687324217816-rf0fgie7b4p4qkrljiab3ro6l4cl82m0.apps.googleusercontent.com',
      iosClientId:
          '687324217816-cjr3p3bhok2mrtsu3e3pqkc3qq0cba7g.apps.googleusercontent.com',
      iosBundleId: 'com.example.capstoneFinalApp',
    );
  }

  static FirebaseOptions get macos {
    return FirebaseOptions(
      apiKey:
          dotenv.env['FIREBASE_API_KEY_IOS'] ??
          '', // Assuming macOS uses the same as iOS
      appId: '1:687324217816:ios:49d746f5829cba230b32ad',
      messagingSenderId: '687324217816',
      projectId: 'sentinel360-final',
      storageBucket: 'sentinel360-final.firebasestorage.app',
      androidClientId:
          '687324217816-rf0fgie7b4p4qkrljiab3ro6l4cl82m0.apps.googleusercontent.com',
      iosClientId:
          '687324217816-cjr3p3bhok2mrtsu3e3pqkc3qq0cba7g.apps.googleusercontent.com',
      iosBundleId: 'com.example.capstoneFinalApp',
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey:
          dotenv.env['FIREBASE_API_KEY_WEB'] ??
          '', // Assuming windows uses the same as web
      appId: '1:687324217816:web:24b2d903005067c10b32ad',
      messagingSenderId: '687324217816',
      projectId: 'sentinel360-final',
      authDomain: 'sentinel360-final.firebaseapp.com',
      storageBucket: 'sentinel360-final.firebasestorage.app',
    );
  }
}
